"""P0 frontend/backend PARITY regression — invisible intra-token chars.

Mirror of test_invisible_intra_token_wordcount_feb2026.py but executes
the FRONTEND `smartScriptParser.ts` through the Node shim in
`_frontend_parser_shim.js`. Locks the contract that the physical APK
reads the SAME `JACK/EMILY/BELLA/LILY` character set as the backend
when PyPDF2 injects an invisible intra-token character into the
document title/subtitle.

Skips gracefully when the Node TypeScript loader is unavailable (same
behaviour as the existing nuclear parity suite).
"""

from __future__ import annotations

import importlib
import json
import os as _os
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "backend"))
server = importlib.import_module("server")
fallback_parse_script = server.fallback_parse_script


_INVISIBLE_CHARS = [
    ("ZWSP",  "\u200B"),
    ("NBSP",  "\u00A0"),
    ("ZWJ",   "\u200D"),
    ("ZWNJ",  "\u200C"),
    ("BOM",   "\uFEFF"),
    ("WJ",    "\u2060"),
    ("INVTIMES", "\u2062"),
    ("CGJ",   "\u034F"),
    ("ALM",   "\u061C"),
    ("MVS",   "\u180E"),
]


def _mk_script(subtitle: str) -> str:
    return "\n".join([
        "THE GREAT SNACK HEIST",
        "",
        subtitle,
        "",
        "INT. KITCHEN - DAY",
        "",
        "JACK",
        "I knew it. The last cookie is gone.",
        "",
        "EMILY",
        "Where?",
        "",
        "BELLA",
        "Apparently.",
        "",
        "LILY",
        "Oh no.",
    ])


def _run_frontend_parser(raw_text: str) -> dict | None:
    shim_path = ROOT / "backend" / "tests" / "_frontend_parser_shim.js"
    if not shim_path.exists():
        # The shim is generated by the nuclear parity suite on first
        # run; regenerate here so this file can run standalone.
        shim_source_path = ROOT / "backend" / "tests" / "test_scriptm8_frontend_backend_parity_feb2026.py"
        src = shim_source_path.read_text(encoding="utf-8")
        start = src.index('FRONTEND_PARSER_SHIM = r"""') + len('FRONTEND_PARSER_SHIM = r"""')
        end = src.index('"""', start)
        shim_path.write_text(src[start:end], encoding="utf-8")
    frontend_node_modules = ROOT / "frontend" / "node_modules"
    env = {
        **_os.environ,
        "NODE_PATH": str(frontend_node_modules),
        "FRONTEND_NODE_MODULES": str(frontend_node_modules),
    }
    try:
        result = subprocess.run(
            ["node", str(shim_path), raw_text],
            cwd=str(ROOT / "frontend"),
            capture_output=True,
            text=True,
            timeout=60,
            env=env,
        )
    except FileNotFoundError:
        return None
    if result.returncode == 2:
        return None
    if result.returncode != 0:
        pytest.fail(
            f"Frontend parser shim failed (rc={result.returncode}):\n"
            f"stdout={result.stdout!r}\nstderr={result.stderr!r}"
        )
    return json.loads(result.stdout)


def _skip_if_no_ts_loader(parsed):
    if parsed is None:
        pytest.skip("Frontend TS parser not runnable in this env.")


@pytest.mark.parametrize("label,ch", _INVISIBLE_CHARS)
def test_frontend_subtitle_SCRIPT_invisible_M8_not_a_character(label: str, ch: str) -> None:
    subtitle = f"SCRIPT{ch}M8 STRESS-TEST SCRIPT"
    parsed = _run_frontend_parser(_mk_script(subtitle))
    _skip_if_no_ts_loader(parsed)
    chars = {str(c).upper().strip() for c in parsed["characters"]}
    assert chars == {"JACK", "EMILY", "BELLA", "LILY"}, (
        f"[FE {label}] subtitle {subtitle!r} leaked. chars={sorted(chars)}"
    )


@pytest.mark.parametrize("label,ch", _INVISIBLE_CHARS)
def test_frontend_subtitle_M8_invisible_STRESS_not_a_character(label: str, ch: str) -> None:
    subtitle = f"SCRIPT M8{ch}STRESS-TEST SCRIPT"
    parsed = _run_frontend_parser(_mk_script(subtitle))
    _skip_if_no_ts_loader(parsed)
    chars = {str(c).upper().strip() for c in parsed["characters"]}
    assert chars == {"JACK", "EMILY", "BELLA", "LILY"}, (
        f"[FE {label}] subtitle {subtitle!r} leaked. chars={sorted(chars)}"
    )


@pytest.mark.parametrize("label,ch", _INVISIBLE_CHARS)
def test_frontend_subtitle_STRESSTEST_invisible_SCRIPT_not_a_character(label: str, ch: str) -> None:
    subtitle = f"SCRIPT M8 STRESS-TEST{ch}SCRIPT"
    parsed = _run_frontend_parser(_mk_script(subtitle))
    _skip_if_no_ts_loader(parsed)
    chars = {str(c).upper().strip() for c in parsed["characters"]}
    assert chars == {"JACK", "EMILY", "BELLA", "LILY"}, (
        f"[FE {label}] subtitle {subtitle!r} leaked. chars={sorted(chars)}"
    )


def test_frontend_title_NBSP_between_tokens_not_a_character() -> None:
    raw = _mk_script("SUBTITLE LINE ONE").replace(
        "THE GREAT SNACK HEIST", "THE\u00A0GREAT SNACK HEIST"
    )
    parsed = _run_frontend_parser(raw)
    _skip_if_no_ts_loader(parsed)
    chars = {str(c).upper().strip() for c in parsed["characters"]}
    assert "THE GREAT SNACK HEIST" not in chars
    assert "THE\u00A0GREAT SNACK HEIST" not in chars
    assert {"JACK", "EMILY", "BELLA", "LILY"}.issubset(chars)


@pytest.mark.parametrize("label,ch", _INVISIBLE_CHARS)
def test_frontend_backend_sets_agree_with_invisible_injection(label: str, ch: str) -> None:
    """The TWO parsers MUST produce the same character identity set
    when PyPDF2 injects an invisible intra-token char into the
    subtitle. Otherwise the review screen and the saved script
    disagree about the cast."""
    subtitle = f"SCRIPT{ch}M8 STRESS-TEST SCRIPT"
    raw = _mk_script(subtitle)
    frontend = _run_frontend_parser(raw)
    _skip_if_no_ts_loader(frontend)
    backend = fallback_parse_script(raw)
    fe_chars = {str(c).upper().strip() for c in frontend["characters"]}
    be_chars = {str(c).upper().strip() for c in backend.get("characters", [])}
    assert fe_chars == be_chars, (
        f"[{label}] FE/BE drift.\nfe={sorted(fe_chars)}\nbe={sorted(be_chars)}"
    )
    assert fe_chars == {"JACK", "EMILY", "BELLA", "LILY"}


if __name__ == "__main__":
    pytest.main([__file__, "-v", "-s"])
